### ISSUE TITLE
No module named 'duckietown'

### ISSUE THREAD

**Issue by wolf2127** [DailyL/Sim2Real_autonomous_vehicle#7]
Hi, when I try to run roslaunch rl_duckietown overtaking.launch, it prompts me with No module named 'duckietown', but I'm in the Sim2Real_autonomous_vehicle/training_ws/build But I can find duckietown in Sim2Real_autonomous_vehicle/training_ws/build folder, what should I do?
![2623ADA0A1E69D74B13F12CCA7976B54](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/dfcac1ba-e2e2-4125-9ab5-536e59313c01)

**Comment by DailyL** [comment]
Have you installed Gym-duckietown? 
$ cd gym-duckietown/
$ pip install -e .

**Comment by DailyL** [comment]
also, please try to install duckietown-shell
$ pip install duckietown-gym-daffy
$ pip install duckietown-shell

**Comment by wolf2127** [comment]
Hello, according to what you said, I downloaded these packages, but still show the following error: ModuleNotFoundError: No module named 'duckietown_msgs'
![Uploading 选区_002.png…]()

**Comment by wolf2127** [comment]
Hello, according to what you said, I downloaded these packages, but still show the following error: ModuleNotFoundError: No module named 'duckietown_msgs'
![选区_002](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/75a4cbf8-fb57-421a-81ee-1f7a0af0ba88)

**Comment by DailyL** [comment]
Have you run 
$ catkin_make 
for the training workspace?

**Comment by wolf2127** [comment]
Yes, I did catkin_make under the training_ws file and it showed a successful compilation.
![选区_006](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/800e3e3a-d9e2-4005-935f-96c4e8ecacba)

**Comment by wolf2127** [comment]
l set the ROS_PACKAGE_PATH in .bashrc

![选区_007](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/850fbf51-fa83-43a4-9858-115d668b97b5)

**Comment by wolf2127** [comment]
The $ROS_PACKAGE_PATH is shown in the following figure
![选区_009](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/adb25911-d019-40d6-a6c7-9431f845b8e4)

**Comment by DailyL** [comment]
Can you try to replace **duckietown_msgs** folder inside the training_ws and catkin make it again? 
Like here(https://blog.csdn.net/aibingjin/article/details/123842052) in step 2.

**Comment by wolf2127** [comment]
Sorry, it's still encountering this error, when I run rosmsg list I find duckietown_msgs in the message list but no instantiate_utils.
![选区_010](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/be891207-4f55-4e3d-9df6-9c0fbbf61334)

**Comment by wolf2127** [comment]
Here's a screenshot after I ran launch

![选区_011](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/53f8c97e-fab5-48db-af49-2ac082b8f036)
![选区_012](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/3b9a4153-c693-4a61-a9f7-68bae5b88c76)
![选区_013](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/a9fa9719-c6a3-4030-b365-c96039714327)
![选区_014](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/c56114c2-14f6-4f7c-8428-aa6d32d86782)
![选区_015](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/f34f5412-d1e5-4d5c-9632-45951f0a3af1)
![选区_016](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/b6e16721-638b-4609-81dc-4be3ac10872e)
![选区_018](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/6788e988-37a8-44aa-a4a5-08690192b3aa)

**Comment by wolf2127** [comment]
No module named 'duckietown' was resolved after I tried to replace the compilation again, but it still shows ModuleNotFoundError: no module named "duckietown_code_utils"
and ModuleNotFoundError: no module named "instantiate_utils"
![选区_019](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/cb305184-bcea-423b-9800-3ff9b53f00fa)
![选区_020](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/b92e31bd-d280-47f8-9d1b-6daa2a331529)

**Comment by DailyL** [comment]
You can run 
$pip install duckietown-utils-daffy 
to install duckietown-utils

**Comment by wolf2127** [comment]
But how to solve this problem, ModuleNotFoundError: No module named 'instantiate_utils' and ImportError: dynamic module does not define module export function (PyInit__tf2)

![选区_022](https://github.com/DailyL/Sim2Real_autonomous_vehicle/assets/116620093/09b07899-fe41-4799-95f6-6143dd6df550)

**Comment by DailyL** [comment]
Hi, it seems you are using Python2, but Python 3 is preferable.
The problem is caused by Python2, see [here](https://answers.ros.org/question/326226/importerror-dynamic-module-does-not-define-module-export-function-pyinit__tf2/).
I have updated the package, I encourage you to remake your workspace again with Python3.

**Comment by wolf2127** [comment]
ok, l will have a try. Thanks for helping me a lot.
